name: Test

on:
  # Disabled by default
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type'
        required: true
        default: 'unit'
        type: choice
        options:
        - unit
        - integration
        - functional

jobs:
  test:
    name: Run ${{ github.event.inputs.test_type }} tests
    runs-on: ubuntu-latest
    if: false  # This line disables the workflow completely

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Test
      run: |
        echo "Test process disabled"
        exit 0
